"""
Tests for import_external_skill - 外部 Skill 导入入口测试

T12: External Skill Governance Entry Point

测试场景覆盖：
1. 成功场景 - 外部 Skill 通过治理流程
2. Forbidden field injection - n8n 越权字段注入阻断
3. Constitution Gate failure - 宪法裁决失败
4. System Audit failure - 系统审计失败
5. run_id/evidence_ref 由 SkillForge 内部生成
6. 输出必须包含 gate_decision + required_changes（失败时）

Contract: docs/2026-02-19/contracts/external_skill_governance_contract_v1.yaml
Job ID: L45-D3-EXT-SKILL-GOV-20260220-003
"""
import json
import os
import sys
import unittest
from pathlib import Path
from datetime import datetime, timezone

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

# Set signing key for gate_permit verification
os.environ["PERMIT_HS256_KEY"] = "test-signing-key-for-unit-tests-2026"


# ============================================================================
# Test Constants
# ============================================================================

TEST_REPO_URL = "https://github.com/external/skill-package"
TEST_COMMIT_SHA = "a1b2c3d4e5f6789012345678901234567890abcd"
TEST_REQUESTER_ID = "user-external-import"
TEST_EXTERNAL_SKILL_REF = "skill://external/example-skill@1.0.0"
JOB_ID = "L45-D3-EXT-SKILL-GOV-20260220-003"
SKILL_ID = "l45_external_skill_governance_batch1"


# ============================================================================
# Helper Functions
# ============================================================================

def now_iso() -> str:
    """Return ISO-8601 UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def generate_run_id() -> str:
    """Generate a unique run ID (SkillForge internal)."""
    import time
    import uuid
    ts = int(time.time())
    uid = uuid.uuid4().hex[:8].upper()
    return f"RUN-N8N-{ts}-{uid}"


def generate_evidence_ref(prefix: str = "EV-N8N") -> str:
    """Generate an evidence reference."""
    import time
    import uuid
    ts = int(time.time())
    uid = uuid.uuid4().hex[:8].upper()
    return f"{prefix}-{ts}-{uid}"


# ============================================================================
# Test Cases
# ============================================================================

class TestImportExternalSkill(unittest.TestCase):
    """
    Tests for import_external_skill endpoint.

    Constraints (T12):
    - run_id/evidence_ref must be generated by SkillForge internally
    - External input cannot inject gate_decision/release_allowed/evidence_ref/run_id
    - Fail-closed on all error branches
    - Response must contain gate_decision + required_changes (on failure)
    """

    # -------------------------------------------------------------------------
    # Test 1: Success case - valid import
    # -------------------------------------------------------------------------
    def test_success_valid_import(self):
        """
        Test 1: Success case with valid external skill import.

        Expected: ok=true, gate_decision=ALLOW, pipeline_state=S6_REGISTRY_ADMISSION
        """
        print("\n=== Test 1: Success - Valid Import ===")

        # Simulate successful import response
        success_envelope = {
            "ok": True,
            "data": {
                "external_skill_ref": TEST_EXTERNAL_SKILL_REF,
                "repo_url": TEST_REPO_URL,
                "commit_sha": TEST_COMMIT_SHA,
                "import_status": "COMPLETED",
                "pipeline_state": "S6_REGISTRY_ADMISSION",
                "quarantine_id": "Q-ABCD1234EFGH",
                "permit_id": "PERMIT-EXT-12345678",
                "registry_entry_id": "REG-1234567890AB",
                "skill_revision": 1,
                "audit_summary": {
                    "L1_contract_audit": {"status": "PASS", "score": 95},
                    "L2_control_audit": {"status": "PASS", "score": 90},
                    "L3_security_audit": {"status": "PASS", "score": 88},
                    "L4_evidence_audit": {"status": "PASS", "score": 92},
                    "L5_reproducibility_audit": {"status": "PASS", "score": 85},
                },
            },
            "gate_decision": "ALLOW",
            "release_allowed": True,
            "evidence_ref": "EV-EXT-SKILL-1234567890-ABCD1234",
            "run_id": "RUN-N8N-1234567890-EFGH5678",
        }

        # Verify required fields
        self.assertTrue(success_envelope["ok"])
        self.assertEqual(success_envelope["gate_decision"], "ALLOW")
        self.assertTrue(success_envelope["release_allowed"])
        self.assertIn("run_id", success_envelope)
        self.assertIn("evidence_ref", success_envelope)

        # Verify pipeline completion
        self.assertEqual(success_envelope["data"]["pipeline_state"], "S6_REGISTRY_ADMISSION")
        self.assertIn("quarantine_id", success_envelope["data"])
        self.assertIn("permit_id", success_envelope["data"])
        self.assertIn("registry_entry_id", success_envelope["data"])

        print(f"  ✓ gate_decision: {success_envelope['gate_decision']}")
        print(f"  ✓ pipeline_state: {success_envelope['data']['pipeline_state']}")
        print(f"  ✓ run_id: {success_envelope['run_id']}")

    # -------------------------------------------------------------------------
    # Test 2: Forbidden field injection detection
    # -------------------------------------------------------------------------
    def test_forbidden_field_injection(self):
        """
        Test 2: Forbidden field injection detection.

        Forbidden fields: gate_decision, release_allowed, evidence_ref, permit_id, run_id
        Expected: BLOCK with required_changes
        """
        print("\n=== Test 2: Forbidden Field Injection ===")

        FORBIDDEN_FIELDS = [
            "gate_decision",
            "release_allowed",
            "evidence_ref",
            "permit_id",
            "run_id",
        ]

        def detect_forbidden_fields(request_dict: dict) -> list:
            found = []
            for field in FORBIDDEN_FIELDS:
                if field in request_dict and request_dict[field] is not None:
                    found.append(field)
            return found

        # Test with all forbidden fields
        malicious_request = {
            "repo_url": TEST_REPO_URL,
            "commit_sha": TEST_COMMIT_SHA,
            "external_skill_ref": TEST_EXTERNAL_SKILL_REF,
            "requester_id": TEST_REQUESTER_ID,
            "gate_decision": "ALLOW",      # FORBIDDEN!
            "release_allowed": True,        # FORBIDDEN!
            "evidence_ref": "EV-FAKE",      # FORBIDDEN!
            "permit_id": "PERMIT-FAKE",     # FORBIDDEN!
            "run_id": "RUN-INJECTED",       # FORBIDDEN!
        }

        forbidden = detect_forbidden_fields(malicious_request)
        print(f"  Detected forbidden fields: {forbidden}")

        # All 5 forbidden fields should be detected
        self.assertEqual(len(forbidden), 5, "All 5 forbidden fields should be detected")
        for field in FORBIDDEN_FIELDS:
            self.assertIn(field, forbidden)

        # Simulate error response
        error_envelope = {
            "ok": False,
            "error_code": "N8N_FORBIDDEN_FIELD_INJECTION",
            "blocked_by": "N8N_POLICY_VIOLATION",
            "message": f"n8n attempted to inject forbidden fields: {forbidden}",
            "gate_decision": "BLOCK",
            "evidence_ref": "EV-EXT-SKILL-1234567890-BLOCK",
            "run_id": "RUN-N8N-1234567890-BLOCK",
            "required_changes": [f"Remove forbidden field '{field}'" for field in forbidden],
        }

        self.assertEqual(error_envelope["gate_decision"], "BLOCK")
        self.assertIn("required_changes", error_envelope)
        self.assertEqual(len(error_envelope["required_changes"]), 5)

        print(f"  ✓ Blocked with gate_decision: {error_envelope['gate_decision']}")
        print(f"  ✓ required_changes: {len(error_envelope['required_changes'])} items")

    # -------------------------------------------------------------------------
    # Test 3: Constitution Gate failure
    # -------------------------------------------------------------------------
    def test_constitution_gate_failure(self):
        """
        Test 3: Constitution Gate failure.

        Expected: BLOCK with required_changes containing violation details
        """
        print("\n=== Test 3: Constitution Gate Failure ===")

        # Invalid repo_url (not HTTPS or git@)
        invalid_request = {
            "repo_url": "ftp://invalid-url",  # Invalid!
            "commit_sha": TEST_COMMIT_SHA,
            "external_skill_ref": TEST_EXTERNAL_SKILL_REF,
            "requester_id": TEST_REQUESTER_ID,
        }

        # Simulate constitution gate check
        constitution_violations = []
        if not invalid_request["repo_url"].startswith(("https://", "git@")):
            constitution_violations.append("repo_url must be a valid git URL")

        self.assertEqual(len(constitution_violations), 1)
        print(f"  Constitution violations: {constitution_violations}")

        # Simulate error response
        error_envelope = {
            "ok": False,
            "error_code": "CONSTITUTION_GATE_FAILED",
            "blocked_by": "CONSTITUTION_VIOLATION",
            "message": f"Constitution gate failed: {constitution_violations}",
            "gate_decision": "BLOCK",
            "evidence_ref": "EV-EXT-SKILL-1234567890-CONST",
            "run_id": "RUN-N8N-1234567890-CONST",
            "required_changes": constitution_violations,
        }

        self.assertEqual(error_envelope["gate_decision"], "BLOCK")
        self.assertIn("required_changes", error_envelope)
        print(f"  ✓ Blocked with required_changes: {error_envelope['required_changes']}")

    # -------------------------------------------------------------------------
    # Test 4: System Audit failure
    # -------------------------------------------------------------------------
    def test_system_audit_failure(self):
        """
        Test 4: System Audit failure (L1-L5).

        Expected: BLOCK with required_changes containing audit failure details
        """
        print("\n=== Test 4: System Audit Failure ===")

        # Simulate audit with failures
        audit_results = {
            "L1_contract_audit": {"status": "PASS", "score": 95},
            "L2_control_audit": {"status": "FAIL", "score": 40},  # FAIL
            "L3_security_audit": {"status": "PASS", "score": 88},
            "L4_evidence_audit": {"status": "PASS", "score": 92},
            "L5_reproducibility_audit": {"status": "FAIL", "score": 30},  # FAIL
        }

        pass_count = sum(1 for r in audit_results.values() if r["status"] == "PASS")
        critical_failures = [k for k, v in audit_results.items() if v["status"] == "FAIL"]

        print(f"  Pass count: {pass_count}/5")
        print(f"  Critical failures: {critical_failures}")

        # Need at least 4/5 to pass
        self.assertLess(pass_count, 4)

        # Build required_changes
        required_changes = [f"Fix {layer}: score too low" for layer in critical_failures]
        required_changes.append(f"Need at least 4/5 layers to pass, got {pass_count}")

        # Simulate error response
        error_envelope = {
            "ok": False,
            "error_code": "SYSTEM_AUDIT_FAILED",
            "blocked_by": "AUDIT_FAILURE",
            "message": f"System audit failed: {pass_count}/5 layers passed",
            "gate_decision": "BLOCK",
            "evidence_ref": "EV-EXT-SKILL-1234567890-AUDIT",
            "run_id": "RUN-N8N-1234567890-AUDIT",
            "required_changes": required_changes,
        }

        self.assertEqual(error_envelope["gate_decision"], "BLOCK")
        self.assertGreater(len(error_envelope["required_changes"]), 0)
        print(f"  ✓ Blocked with required_changes: {error_envelope['required_changes']}")

    # -------------------------------------------------------------------------
    # Test 5: run_id and evidence_ref generated by SkillForge
    # -------------------------------------------------------------------------
    def test_run_id_evidence_ref_skillforge_generated(self):
        """
        Test 5: run_id and evidence_ref must be SkillForge-generated.

        Format:
        - run_id: RUN-N8N-{timestamp}-{8位UID}
        - evidence_ref: EV-EXT-SKILL-{timestamp}-{8位UID}
        """
        print("\n=== Test 5: run_id/evidence_ref SkillForge Generated ===")

        run_id = generate_run_id()
        evidence_ref = generate_evidence_ref("EV-EXT-SKILL")

        print(f"  run_id: {run_id}")
        print(f"  evidence_ref: {evidence_ref}")

        # Verify run_id format
        self.assertTrue(run_id.startswith("RUN-N8N-"), f"run_id should start with RUN-N8N-")
        parts = run_id.split("-")
        self.assertGreaterEqual(len(parts), 4)

        # Verify evidence_ref format
        self.assertTrue(evidence_ref.startswith("EV-EXT-SKILL-"), f"evidence_ref should start with EV-EXT-SKILL-")

        print("  ✓ run_id format verified")
        print("  ✓ evidence_ref format verified")

    # -------------------------------------------------------------------------
    # Test 6: Output envelope contains required fields
    # -------------------------------------------------------------------------
    def test_output_envelope_required_fields(self):
        """
        Test 6: Output must contain required fields.

        Required for success: run_id, gate_decision, evidence_ref, release_allowed
        Required for failure: run_id, gate_decision, evidence_ref, required_changes
        """
        print("\n=== Test 6: Output Envelope Required Fields ===")

        # Success envelope required fields
        success_required = ["run_id", "gate_decision", "evidence_ref", "release_allowed"]
        success_envelope = {
            "ok": True,
            "data": {},
            "gate_decision": "ALLOW",
            "release_allowed": True,
            "evidence_ref": "EV-TEST",
            "run_id": "RUN-TEST",
        }

        for field in success_required:
            self.assertIn(field, success_envelope, f"Missing required field: {field}")
            print(f"  ✓ Success envelope has: {field}")

        # Error envelope required fields
        error_required = ["run_id", "gate_decision", "evidence_ref", "required_changes"]
        error_envelope = {
            "ok": False,
            "error_code": "TEST",
            "blocked_by": "TEST",
            "message": "Test",
            "gate_decision": "BLOCK",
            "evidence_ref": "EV-TEST",
            "run_id": "RUN-TEST",
            "required_changes": ["Fix X"],
        }

        for field in error_required:
            self.assertIn(field, error_envelope, f"Missing required field: {field}")
            print(f"  ✓ Error envelope has: {field}")

    # -------------------------------------------------------------------------
    # Test 7: Fail-closed on all error paths
    # -------------------------------------------------------------------------
    def test_fail_closed_all_paths(self):
        """
        Test 7: All error paths must be fail-closed.

        Verify: gate_decision=BLOCK for all error scenarios
        """
        print("\n=== Test 7: Fail-Closed All Paths ===")

        error_scenarios = [
            ("N8N_FORBIDDEN_FIELD_INJECTION", "Forbidden field injection"),
            ("CONSTITUTION_GATE_FAILED", "Constitution violation"),
            ("SYSTEM_AUDIT_FAILED", "Audit failure"),
            ("IMPORT_INTERNAL_ERROR", "Internal error"),
        ]

        for error_code, description in error_scenarios:
            # All error responses must have gate_decision=BLOCK
            error_envelope = {
                "ok": False,
                "error_code": error_code,
                "gate_decision": "BLOCK",
                "required_changes": ["Fix the issue"],
            }
            self.assertEqual(error_envelope["gate_decision"], "BLOCK")
            self.assertIn("required_changes", error_envelope)
            print(f"  ✓ {error_code}: gate_decision={error_envelope['gate_decision']}")

    # -------------------------------------------------------------------------
    # Test 8: Import pipeline states
    # -------------------------------------------------------------------------
    def test_import_pipeline_states(self):
        """
        Test 8: Import pipeline states.

        Verify all 6 states are defined per contract.
        """
        print("\n=== Test 8: Import Pipeline States ===")

        IMPORT_PIPELINE_STATES = [
            "S1_QUARANTINE",
            "S2_CONSTITUTION_GATE",
            "S3_SYSTEM_AUDIT",
            "S4_DECISION",
            "S5_PERMIT_ISSUANCE",
            "S6_REGISTRY_ADMISSION",
        ]

        self.assertEqual(len(IMPORT_PIPELINE_STATES), 6)
        for state in IMPORT_PIPELINE_STATES:
            print(f"  ✓ {state}")

        # Verify final state on success
        success_response = {
            "pipeline_state": "S6_REGISTRY_ADMISSION",
            "import_status": "COMPLETED",
        }
        self.assertEqual(success_response["pipeline_state"], "S6_REGISTRY_ADMISSION")
        print("  ✓ Final state on success: S6_REGISTRY_ADMISSION")


# ============================================================================
# Main
# ============================================================================

if __name__ == "__main__":
    unittest.main(verbosity=2)
